<?php

class Arsip_model extends CI_Model
{    
    function tampil()
    {
        return $this->db->query('SELECT * FROM arsip a, kategori b WHERE a.id_kategori=b.id_kategori');
        //SELECT * FROM arsip
    }

    function simpan($data,$table)
    {
        return $this->db->insert($table,$data);
        //insert into arsip value('id_kategor','arsip');
    }

    function edit_data($where,$table)
    {
        return $this->db->get_where($table,$where);
    }

    function edit_simpan($where,$data,$table)
    {
        $this->db->where($where);
        $this->db->update($table,$data);
    }

    function hapus($where,$table)
    {
        $this->db->where($where);
        $this->db->delete($table);
    }
}


/* End of file Ptk_model.php */
/* Location: ./application/models/Ptk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-31 01:06:47 */
/* http://harviacode.com */