<?php

class Laporan_model extends CI_Model
{    
    function tampil()
    {
        return $this->db->query('SELECT * FROM arsip a, kategori b WHERE a.id_kategori=b.id_kategori');
        //SELECT * FROM arsip
    }

   function cari($data)
   {
    $this->db->from('arsip');
   $this->db-where('tgl_arsip>=',$this->input->post('tgl_awal'));
    $this->db-where('tgl_arsip>=',$this->input->post('tgl_akhir'));
    $query=$this->db->get();
    return $query->result();
   }
}


/* End of file Ptk_model.php */
/* Location: ./application/models/Ptk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-31 01:06:47 */
/* http://harviacode.com */